Resources:
  LLMResearchVPC:
    Type: AWS::EC2::VPC
    Properties:
      InstanceTenancy: default
      CidrBlock: 172.31.0.0/16
  LLMResearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: default VPC security group
      GroupName: LLMResearchSecurityGroup
      VpcId: !Ref LLMResearchVPC
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LLMResearchVPC
      MapPublicIpOnLaunch: true
      CidrBlock: 172.31.0.0/20
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LLMResearchVPC
      MapPublicIpOnLaunch: true
      CidrBlock: 172.31.16.0/20
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref LLMResearchVPC
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LLMResearchVPC
  RoutingInVPC:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref RouteTable
  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref RouteTable
  LLMResearchComputeEnv:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: LLMResearchComputeEnv  # the attempt to update the stack on CloudFormation
      # raises an error "Cannot update custom-named Compute environment
      ComputeResources:
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        DesiredvCpus: 1  # For some reason, after stack deployment and after job run this value drops to 0,
        # so one needs to return it to 1 manually after each job run
        MaxvCpus: 1
        MinvCpus: 0
        InstanceRole:
          !Join
            - ''
            - - 'arn:aws:iam::'
              - !Ref AWS::AccountId
              - ':instance-profile/ecsInstanceRole'
        InstanceTypes:
          - "p2.xlarge"
        SecurityGroupIds:
          - !Ref LLMResearchSecurityGroup
        Subnets:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
        Type: EC2
        UpdateToLatestImageVersion: true
      ReplaceComputeEnvironment: true
      State: ENABLED
      Type: MANAGED
      UpdatePolicy:  # didn't find a corresponding parameter in terraform
        JobExecutionTimeoutMinutes: 30
        TerminateJobsOnUpdate: false
  LLMResearchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment:
            !Join
            - ':'
            - - 'arn:aws:batch'
              - !Ref AWS::Region
              - !Ref AWS::AccountId
              - 'compute-environment/LLMResearchComputeEnv'
          Order: 1
      JobQueueName: LLMResearchJobQueue
      Priority: 0
      State: ENABLED
    DependsOn: LLMResearchComputeEnv
  HelloWorldAllDefaultsJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      ContainerProperties:
        Command:
          - echo
          - hello world
        Image: public.ecr.aws/amazonlinux/amazonlinux:latest
        LogConfiguration:
          LogDriver: awslogs
        ResourceRequirements:
          - Type: MEMORY
            Value: 2048
          - Type: VCPU
            Value: 1
          - Type: GPU
            Value: 1
      JobDefinitionName: HelloWorldAllDefaultsJobDefinition
      PlatformCapabilities:
        - EC2
      PropagateTags: true
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: 3600
      Type: container
